# Generated by Django 5.2.7 on 2025-10-18 10:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.CharField(max_length=500, verbose_name='Cevap Metni')),
                ('dogru_mu', models.BooleanField(default=False, verbose_name='Doğru mu?')),
            ],
            options={
                'verbose_name': 'Cevap',
                'verbose_name_plural': 'Cevaplar',
            },
        ),
        migrations.CreateModel(
            name='Konu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, unique=True, verbose_name='Konu Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra Numarası')),
            ],
            options={
                'verbose_name': 'Konu',
                'verbose_name_plural': 'Konular',
                'ordering': ['sira', 'isim'],
            },
        ),
        migrations.CreateModel(
            name='Rozet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, unique=True, verbose_name='Rozet Adı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('ikon', models.CharField(default='🏆', max_length=50, verbose_name='İkon (Emoji)')),
                ('kosul_turu', models.CharField(choices=[('soru_sayisi', 'Çözülen Soru Sayısı'), ('toplam_puan', 'Toplam Puan'), ('dogru_sayisi', 'Toplam Doğru Sayısı'), ('basari_orani', 'Başarı Oranı'), ('seri', 'Seri (Üst Üste Doğru)')], max_length=50, verbose_name='Koşul Türü')),
                ('kosul_degeri', models.IntegerField(verbose_name='Koşul Değeri')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Rozet',
                'verbose_name_plural': 'Rozetler',
                'ordering': ['sira', 'kosul_degeri'],
            },
        ),
        migrations.CreateModel(
            name='TabuKelime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime', models.CharField(max_length=100, unique=True, verbose_name='Tabu Kelime')),
            ],
            options={
                'verbose_name': 'Tabu Kelime',
                'verbose_name_plural': 'Tabu Kelimeler',
            },
        ),
        migrations.CreateModel(
            name='TabuOyun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takim_a_adi', models.CharField(default='Takım A', max_length=100)),
                ('takim_b_adi', models.CharField(default='Takım B', max_length=100)),
                ('takim_a_skor', models.IntegerField(default=0)),
                ('takim_b_skor', models.IntegerField(default=0)),
                ('aktif_takim', models.CharField(choices=[('A', 'Takım A'), ('B', 'Takım B')], default='A', max_length=1)),
                ('oyun_durumu', models.CharField(choices=[('devam_ediyor', 'Devam Ediyor'), ('bitti', 'Bitti')], default='devam_ediyor', max_length=20)),
                ('oyun_modu', models.CharField(choices=[('normal', 'Normal'), ('uzatma', 'Uzatma')], default='normal', max_length=20)),
                ('tur_sayisi', models.IntegerField(default=1)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tabu Oyunu',
                'verbose_name_plural': 'Tabu Oyunları',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='KarsilasmaOdasi',
            fields=[
                ('oda_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oyuncu1_skor', models.IntegerField(default=0, verbose_name='Oyuncu 1 Skoru')),
                ('oyuncu2_skor', models.IntegerField(default=0, verbose_name='Oyuncu 2 Skoru')),
                ('oyuncu1_dogru', models.IntegerField(default=0, verbose_name='Oyuncu 1 Doğru Sayısı')),
                ('oyuncu1_yanlis', models.IntegerField(default=0, verbose_name='Oyuncu 1 Yanlış Sayısı')),
                ('oyuncu2_dogru', models.IntegerField(default=0, verbose_name='Oyuncu 2 Doğru Sayısı')),
                ('oyuncu2_yanlis', models.IntegerField(default=0, verbose_name='Oyuncu 2 Yanlış Sayısı')),
                ('oyun_durumu', models.CharField(choices=[('bekleniyor', 'Bekleniyor'), ('oynaniyor', 'Oynanıyor'), ('bitti', 'Bitti')], default='bekleniyor', max_length=20)),
                ('aktif_soru_no', models.IntegerField(default=1, verbose_name='Aktif Soru Numarası')),
                ('toplam_soru', models.IntegerField(default=5, verbose_name='Toplam Soru Sayısı')),
                ('oyuncu1_cevapladi', models.BooleanField(default=False)),
                ('oyuncu2_cevapladi', models.BooleanField(default=False)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('ilk_dogru_cevaplayan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilk_cevaplayan', to=settings.AUTH_USER_MODEL)),
                ('oyuncu1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karsilasma_oyuncu1', to=settings.AUTH_USER_MODEL)),
                ('oyuncu2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karsilasma_oyuncu2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Karşılaşma Odası',
                'verbose_name_plural': 'Karşılaşma Odaları',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.TextField(verbose_name='Soru Metni')),
                ('zorluk', models.CharField(choices=[('kolay', 'Kolay'), ('orta', 'Orta'), ('zor', 'Zor')], default='orta', max_length=20, verbose_name='Zorluk Seviyesi')),
                ('konu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorular', to='quiz.konu')),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
            },
        ),
        migrations.CreateModel(
            name='KullaniciCevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogru_mu', models.BooleanField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.karsilasmaodasi')),
                ('verilen_cevap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.cevap')),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.soru')),
            ],
            options={
                'verbose_name': 'Kullanıcı Cevabı',
                'verbose_name_plural': 'Kullanıcı Cevapları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='aktif_soru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.soru', verbose_name='Aktif Soru'),
        ),
        migrations.AddField(
            model_name='cevap',
            name='soru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to='quiz.soru'),
        ),
        migrations.CreateModel(
            name='YasakliKelime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yasakli_kelime', models.CharField(max_length=100, verbose_name='Yasaklı Kelime')),
                ('tabu_kelime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yasakli_kelimeler', to='quiz.tabukelime')),
            ],
            options={
                'verbose_name': 'Yasaklı Kelime',
                'verbose_name_plural': 'Yasaklı Kelimeler',
            },
        ),
        migrations.CreateModel(
            name='KullaniciRozet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kazanma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rozetler', to=settings.AUTH_USER_MODEL)),
                ('rozet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.rozet')),
            ],
            options={
                'verbose_name': 'Kullanıcı Rozeti',
                'verbose_name_plural': 'Kullanıcı Rozetleri',
                'ordering': ['-kazanma_tarihi'],
                'unique_together': {('kullanici', 'rozet')},
            },
        ),
    ]
