# Generated by Django 5.2.7 on 2025-10-11 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.CharField(max_length=255)),
                ('dogru_mu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Konu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(default='Genel Konu', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TabuKelime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabuOyun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takim_a_adi', models.CharField(default='Takım A', max_length=50)),
                ('takim_b_adi', models.CharField(default='Takım B', max_length=50)),
                ('takim_a_skor', models.IntegerField(default=0)),
                ('takim_b_skor', models.IntegerField(default=0)),
                ('aktif_takim', models.CharField(choices=[('A', 'Takım A'), ('B', 'Takım B')], default='A', max_length=1)),
                ('oyun_durumu', models.CharField(default='baslamadi', max_length=20)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('tur_sayisi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.TextField()),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.konu')),
            ],
        ),
        migrations.CreateModel(
            name='KullaniciCevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verilen_cevap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.cevap')),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.soru')),
            ],
        ),
        migrations.AddField(
            model_name='cevap',
            name='soru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.soru'),
        ),
        migrations.CreateModel(
            name='TabuYasakliKelime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yasakli_kelime', models.CharField(max_length=100)),
                ('ana_kelime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yasakli_kelimeler', to='quiz.tabukelime')),
            ],
        ),
    ]
