# Generated by Django 5.2.7 on 2025-10-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soru',
            name='zorluk',
        ),
        migrations.AddField(
            model_name='soru',
            name='baslik',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='soru',
            name='bul_bakalimda_cikar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='soru',
            name='karsilasmada_cikar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='soru',
            name='sinav_tipi',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='soru',
            name='metin',
            field=models.TextField(),
        ),
    ]
