# Generated by Django 5.2.7 on 2025-10-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabuoyun',
            name='oyun_modu',
            field=models.CharField(choices=[('normal', 'Normal'), ('uzatma', 'Uzatma')], default='normal', max_length=10),
        ),
    ]
