# Generated by Django 5.2.7 on 2025-10-19 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulBakalimOyun',
            fields=[
                ('oyun_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oyun_durumu', models.CharField(choices=[('devam_ediyor', 'Devam Ediyor'), ('bitti', 'Bitti')], default='devam_ediyor', max_length=20)),
                ('dogru_sayisi', models.IntegerField(default=0)),
                ('yanlis_sayisi', models.IntegerField(default=0)),
                ('toplam_puan', models.IntegerField(default=0)),
                ('sorular', models.JSONField(default=list)),
                ('cevaplar', models.JSONField(default=dict)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('bitirme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('oyuncu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bul_bakalim_oyunlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bul Bakalım Oyunu',
                'verbose_name_plural': 'Bul Bakalım Oyunları',
                'db_table': 'bul_bakalim_oyun',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
