# Generated by Django 5.2.7 on 2025-10-11 13:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_tabuoyun_oyun_modu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KarsilasmaOdasi',
            fields=[
                ('oda_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oyuncu1_skor', models.IntegerField(default=0)),
                ('oyuncu2_skor', models.IntegerField(default=0)),
                ('oyun_durumu', models.CharField(choices=[('bekleniyor', 'Rakip Bekleniyor'), ('oynaniyor', 'Oynanıyor'), ('bitti', 'Bitti')], default='bekleniyor', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oyuncu1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oyun_odalari1', to=settings.AUTH_USER_MODEL)),
                ('oyuncu2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oyun_odalari2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
