# Generated by Django 5.2.7 on 2025-10-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_bulbakalimoyun'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulbakalimoyun',
            name='selected_ders',
            field=models.CharField(blank=True, choices=[('matematik', 'Matematik'), ('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe')], max_length=20, null=True, verbose_name='Seçilen Ders'),
        ),
    ]
