# Generated by Django 5.2.7 on 2025-11-04 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_soru_zorluk_soru_baslik_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulbakalimoyun',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bulbakalimoyun',
            name='oyun_durumu',
            field=models.CharField(choices=[('devam_ediyor', 'Devam Ediyor'), ('bitti', 'Bitti')], db_index=True, default='devam_ediyor', max_length=20),
        ),
        migrations.AlterField(
            model_name='bulbakalimoyun',
            name='selected_ders',
            field=models.CharField(blank=True, choices=[('matematik', 'Matematik'), ('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('biyoloji', 'Biyoloji')], db_index=True, max_length=20, null=True, verbose_name='Seçilen Ders'),
        ),
        migrations.AlterField(
            model_name='bulbakalimoyun',
            name='sinav_tipi',
            field=models.CharField(blank=True, choices=[('tyt', 'TYT'), ('ayt', 'AYT')], db_index=True, max_length=10, null=True, verbose_name='Sınav Tipi'),
        ),
        migrations.AlterField(
            model_name='cevap',
            name='dogru_mu',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Doğru mu?'),
        ),
        migrations.AlterField(
            model_name='karsilasmaodasi',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='karsilasmaodasi',
            name='oyun_durumu',
            field=models.CharField(choices=[('bekleniyor', 'Bekleniyor'), ('oynaniyor', 'Oynanıyor'), ('bitti', 'Bitti')], db_index=True, default='bekleniyor', max_length=20),
        ),
        migrations.AlterField(
            model_name='konu',
            name='ders',
            field=models.CharField(choices=[('matematik', 'Matematik'), ('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('biyoloji', 'Biyoloji')], db_index=True, default='matematik', max_length=20, verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='konu',
            name='sira',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='kullanicicevap',
            name='dogru_mu',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='kullanicicevap',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='kullanicirozet',
            name='kazanma_tarihi',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='rozet',
            name='kosul_turu',
            field=models.CharField(choices=[('soru_sayisi', 'Çözülen Soru Sayısı'), ('toplam_puan', 'Toplam Puan'), ('dogru_sayisi', 'Toplam Doğru Sayısı'), ('basari_orani', 'Başarı Oranı'), ('seri', 'Seri (Üst Üste Doğru)')], db_index=True, max_length=50, verbose_name='Koşul Türü'),
        ),
        migrations.AlterField(
            model_name='rozet',
            name='sira',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='soru',
            name='bul_bakalimda_cikar',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='soru',
            name='ders',
            field=models.CharField(choices=[('matematik', 'Matematik'), ('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('biyoloji', 'Biyoloji')], db_index=True, default='matematik', max_length=20, verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='soru',
            name='karsilasmada_cikar',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='soru',
            name='sinav_tipi',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tabukelime',
            name='kategori',
            field=models.CharField(choices=[('biyoloji', 'Biyoloji'), ('kimya', 'Kimya'), ('fizik', 'Fizik'), ('cografya', 'Coğrafya'), ('tarih', 'Tarih'), ('edebiyat', 'Edebiyat')], db_index=True, max_length=30, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='tabuoyun',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tabuoyun',
            name='oyun_durumu',
            field=models.CharField(choices=[('devam_ediyor', 'Devam Ediyor'), ('bitti', 'Bitti')], db_index=True, default='devam_ediyor', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bulbakalimoyun',
            index=models.Index(fields=['oyuncu', '-olusturulma_tarihi'], name='bb_oyuncu_tarih_idx'),
        ),
        migrations.AddIndex(
            model_name='bulbakalimoyun',
            index=models.Index(fields=['oyuncu', 'oyun_durumu'], name='bb_oyuncu_durum_idx'),
        ),
        migrations.AddIndex(
            model_name='cevap',
            index=models.Index(fields=['soru', 'dogru_mu'], name='cevap_soru_dogru_idx'),
        ),
        migrations.AddIndex(
            model_name='karsilasmaodasi',
            index=models.Index(fields=['oyun_durumu', '-olusturma_tarihi'], name='oda_durum_tarih_idx'),
        ),
        migrations.AddIndex(
            model_name='karsilasmaodasi',
            index=models.Index(fields=['oyuncu1', 'oyun_durumu'], name='oda_oyuncu1_durum_idx'),
        ),
        migrations.AddIndex(
            model_name='karsilasmaodasi',
            index=models.Index(fields=['oyuncu2', 'oyun_durumu'], name='oda_oyuncu2_durum_idx'),
        ),
        migrations.AddIndex(
            model_name='konu',
            index=models.Index(fields=['ders', 'sira'], name='konu_ders_sira_idx'),
        ),
        migrations.AddIndex(
            model_name='kullanicicevap',
            index=models.Index(fields=['kullanici', '-tarih'], name='cevap_kullanici_idx'),
        ),
        migrations.AddIndex(
            model_name='kullanicicevap',
            index=models.Index(fields=['kullanici', 'dogru_mu'], name='cevap_kullanici_dogru_idx'),
        ),
        migrations.AddIndex(
            model_name='kullanicirozet',
            index=models.Index(fields=['kullanici', '-kazanma_tarihi'], name='kulrozet_kullanici_idx'),
        ),
        migrations.AddIndex(
            model_name='soru',
            index=models.Index(fields=['ders', 'bul_bakalimda_cikar'], name='soru_ders_bb_idx'),
        ),
        migrations.AddIndex(
            model_name='soru',
            index=models.Index(fields=['ders', 'karsilasmada_cikar'], name='soru_ders_kar_idx'),
        ),
        migrations.AddIndex(
            model_name='soru',
            index=models.Index(fields=['bul_bakalimda_cikar', 'ders'], name='soru_bb_ders_idx'),
        ),
    ]
