# Generated by Django 5.2.7 on 2025-10-12 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_karsilasmaodasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='aktif_soru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.soru'),
        ),
    ]
