# Generated by Django 5.2.7 on 2025-10-19 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_bulbakalimoyun_selected_ders'),
    ]

    operations = [
        migrations.AddField(
            model_name='soru',
            name='ders',
            field=models.CharField(choices=[('matematik', 'Matematik'), ('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe')], default='matematik', max_length=20, verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='soru',
            name='konu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.konu', verbose_name='Konu'),
        ),
        migrations.AlterField(
            model_name='soru',
            name='zorluk',
            field=models.CharField(choices=[('kolay', 'Kolay'), ('orta', 'Orta'), ('zor', 'Zor')], max_length=20, verbose_name='Zorluk Seviyesi'),
        ),
    ]
