# Generated by Django 5.2.7 on 2025-11-04 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_bulbakalimoyun_olusturulma_tarihi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='aktif_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='oyuncu1_combo',
            field=models.IntegerField(default=0, verbose_name='Oyuncu 1 Combo'),
        ),
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='oyuncu1_hizli_cevap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='oyuncu2_combo',
            field=models.IntegerField(default=0, verbose_name='Oyuncu 2 Combo'),
        ),
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='oyuncu2_hizli_cevap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='round_bitis_zamani',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='round_bitti',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='toplam_round',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='OyunMesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj_tipi', models.CharField(choices=[('emoji', 'Emoji'), ('hizli_mesaj', 'Hızlı Mesaj')], max_length=20)),
                ('icerik', models.CharField(max_length=100)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='quiz.karsilasmaodasi')),
            ],
            options={
                'ordering': ['-olusturma_tarihi'],
                'indexes': [models.Index(fields=['oda', '-olusturma_tarihi'], name='quiz_oyunme_oda_id_c6f39c_idx')],
            },
        ),
    ]
