# Generated by Django 5.2.7 on 2025-10-12 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_karsilasmaodasi_aktif_soru'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='ilk_dogru_cevaplayan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='oyuncu1_cevapladi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='oyuncu2_cevapladi',
            field=models.BooleanField(default=False),
        ),
    ]
