# Generated by Django 5.2.7 on 2025-10-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_soru_ders_alter_soru_konu_alter_soru_zorluk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='konu',
            options={'ordering': ['sira']},
        ),
        migrations.RemoveField(
            model_name='konu',
            name='aciklama',
        ),
        migrations.AddField(
            model_name='konu',
            name='ders',
            field=models.CharField(choices=[('matematik', 'Matematik'), ('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe')], default='matematik', max_length=20, verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='konu',
            name='isim',
            field=models.CharField(max_length=100, verbose_name='Konu İsmi'),
        ),
        migrations.AlterField(
            model_name='konu',
            name='sira',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıra'),
        ),
    ]
