# Generated by Django 5.2.7 on 2025-11-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_karsilasmaodasi_aktif_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='oyuncu1_cevap_zamani',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='oyuncu2_cevap_zamani',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='soru_baslangic_zamani',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
