# Generated by Django 5.2.7 on 2025-11-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_karsilasmaodasi_oyuncu1_cevap_zamani_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='ara_ekran_bekleniyor',
            field=models.BooleanField(default=False, verbose_name='Ara Ekran Bekleniyor'),
        ),
    ]
