# Generated by Django 5.2.7 on 2025-10-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_konu_options_remove_konu_aciklama_konu_ders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulbakalimoyun',
            name='selected_ders',
            field=models.CharField(blank=True, choices=[('matematik', 'Matematik'), ('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('biyoloji', 'Biyoloji')], max_length=20, null=True, verbose_name='Seçilen Ders'),
        ),
        migrations.AlterField(
            model_name='konu',
            name='ders',
            field=models.CharField(choices=[('matematik', 'Matematik'), ('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('biyoloji', 'Biyoloji')], default='matematik', max_length=20, verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='soru',
            name='ders',
            field=models.CharField(choices=[('matematik', 'Matematik'), ('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('biyoloji', 'Biyoloji')], default='matematik', max_length=20, verbose_name='Ders'),
        ),
    ]
