# Generated by Django 5.2.7 on 2025-11-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_karsilasmaodasi_ara_ekran_bekleniyor'),
    ]

    operations = [
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='secilen_ders',
            field=models.CharField(choices=[('matematik', 'Matematik'), ('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('biyoloji', 'Biyoloji'), ('karisik', 'Karışık')], db_index=True, default='karisik', max_length=20, verbose_name='Seçilen Ders'),
        ),
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='sinav_tipi',
            field=models.CharField(choices=[('tyt', 'TYT'), ('ayt', 'AYT')], db_index=True, default='ayt', max_length=10, verbose_name='Sınav Tipi'),
        ),
    ]
