# Generated by Django 5.2.7 on 2025-10-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_bulbakalimoyun_selected_ders_alter_konu_ders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulbakalimoyun',
            name='sinav_tipi',
            field=models.CharField(blank=True, choices=[('tyt', 'TYT'), ('ayt', 'AYT')], max_length=10, null=True, verbose_name='Sınav Tipi'),
        ),
    ]
