# Generated by Django 4.2.7 on 2025-11-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_karsilasmaodasi_secilen_ders_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karsilasmaodasi',
            old_name='round_bitti',
            new_name='round_bekleme_durumu',
        ),
    ]
