# Generated by Django 4.2.7 on 2025-12-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_rename_round_bitti_karsilasmaodasi_round_bekleme_durumu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabukelime',
            name='kategori',
            field=models.CharField(choices=[('biyoloji', 'Biyoloji'), ('kimya', 'Kimya'), ('fizik', 'Fizik'), ('cografya', 'Coğrafya'), ('tarih', 'Tarih'), ('edebiyat', 'Edebiyat'), ('felsefe', 'Felsefe')], db_index=True, max_length=30, verbose_name='Kategori'),
        ),
    ]
