# Generated by Django 4.2.7 on 2026-02-18 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0009_alter_tabukelime_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnuva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnuva_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('isim', models.CharField(max_length=200, verbose_name='Turnuva İsmi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('kayit_baslangic', models.DateTimeField(db_index=True, verbose_name='Kayıt Başlangıç')),
                ('kayit_bitis', models.DateTimeField(db_index=True, verbose_name='Kayıt Bitiş')),
                ('baslangic', models.DateTimeField(db_index=True, verbose_name='Turnuva Başlangıç')),
                ('bitis', models.DateTimeField(blank=True, null=True, verbose_name='Turnuva Bitiş')),
                ('sinav_tipi', models.CharField(choices=[('TYT', 'TYT'), ('AYT', 'AYT')], default='AYT', max_length=10)),
                ('ders', models.CharField(default='karisik', max_length=50)),
                ('toplam_soru', models.IntegerField(default=10, verbose_name='Toplam Soru Sayısı')),
                ('max_katilimci', models.IntegerField(default=32, verbose_name='Maksimum Katılımcı')),
                ('odul_xp_1', models.IntegerField(default=1000, verbose_name='1. Ödül XP')),
                ('odul_xp_2', models.IntegerField(default=500, verbose_name='2. Ödül XP')),
                ('odul_xp_3', models.IntegerField(default=250, verbose_name='3. Ödül XP')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('kayit_acik', 'Kayıt Açık'), ('basladi', 'Başladı'), ('devam_ediyor', 'Devam Ediyor'), ('bitti', 'Bitti')], db_index=True, default='beklemede', max_length=20)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('birinci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birinci_turnuvalar', to=settings.AUTH_USER_MODEL)),
                ('ikinci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ikinci_turnuvalar', to=settings.AUTH_USER_MODEL)),
                ('katilimcilar', models.ManyToManyField(blank=True, related_name='turnuvalar', to=settings.AUTH_USER_MODEL)),
                ('ucuncu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ucuncu_turnuvalar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turnuva',
                'verbose_name_plural': 'Turnuvalar',
                'ordering': ['-baslangic'],
            },
        ),
        migrations.CreateModel(
            name='TurnuvaMaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('round', models.IntegerField(choices=[(1, '1/16 Final'), (2, '1/8 Final'), (3, 'Çeyrek Final'), (4, 'Yarı Final'), (5, 'Final')], db_index=True, verbose_name='Tur')),
                ('oyuncu1_skor', models.IntegerField(default=0)),
                ('oyuncu2_skor', models.IntegerField(default=0)),
                ('tamamlandi', models.BooleanField(db_index=True, default=False)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('mac_tarihi', models.DateTimeField(blank=True, null=True)),
                ('karsilasma_oda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.karsilasmaodasi')),
                ('kazanan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kazanilan_turnuva_maclari', to=settings.AUTH_USER_MODEL)),
                ('oyuncu1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnuva_mac_oyuncu1', to=settings.AUTH_USER_MODEL)),
                ('oyuncu2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnuva_mac_oyuncu2', to=settings.AUTH_USER_MODEL)),
                ('turnuva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maclar', to='quiz.turnuva')),
            ],
            options={
                'verbose_name': 'Turnuva Maçı',
                'verbose_name_plural': 'Turnuva Maçları',
                'ordering': ['round', 'olusturma_tarihi'],
                'indexes': [models.Index(fields=['turnuva', 'round'], name='mac_turnuva_round_idx'), models.Index(fields=['turnuva', 'tamamlandi'], name='mac_turnuva_tamamlandi_idx')],
            },
        ),
        migrations.CreateModel(
            name='TurnuvaKatilim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katilim_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sira', models.IntegerField(default=0)),
                ('elendi', models.BooleanField(db_index=True, default=False)),
                ('elenme_turu', models.IntegerField(blank=True, null=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnuva_katilimlari', to=settings.AUTH_USER_MODEL)),
                ('turnuva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='katilimlar', to='quiz.turnuva')),
            ],
            options={
                'verbose_name': 'Turnuva Katılım',
                'verbose_name_plural': 'Turnuva Katılımları',
                'ordering': ['sira'],
                'indexes': [models.Index(fields=['turnuva', 'sira'], name='katilim_turnuva_sira_idx'), models.Index(fields=['kullanici', '-katilim_tarihi'], name='katilim_kullanici_idx')],
                'unique_together': {('turnuva', 'kullanici')},
            },
        ),
        migrations.AddIndex(
            model_name='turnuva',
            index=models.Index(fields=['durum', '-baslangic'], name='turnuva_durum_idx'),
        ),
        migrations.AddIndex(
            model_name='turnuva',
            index=models.Index(fields=['kayit_baslangic', 'kayit_bitis'], name='turnuva_kayit_idx'),
        ),
    ]
