# Generated by Django 4.2.7 on 2026-02-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_turnuva_turnuvamaci_turnuvakatilim_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='konu',
            options={'ordering': ['sira'], 'verbose_name': 'Konu', 'verbose_name_plural': 'Konular'},
        ),
        migrations.AlterField(
            model_name='soru',
            name='baslik',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='soru',
            name='bul_bakalimda_cikar',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Bul Bakalımda Çıksın'),
        ),
        migrations.AlterField(
            model_name='soru',
            name='karsilasmada_cikar',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Karşılaşmada Çıksın'),
        ),
        migrations.AlterField(
            model_name='soru',
            name='metin',
            field=models.TextField(verbose_name='Soru Metni'),
        ),
        migrations.AlterField(
            model_name='soru',
            name='sinav_tipi',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10, verbose_name='Sınav Tipi'),
        ),
        migrations.AlterField(
            model_name='turnuvamaci',
            name='round',
            field=models.IntegerField(choices=[(1, 'Round 1'), (2, 'Round 2'), (3, 'Round 3'), (4, 'Round 4'), (5, 'Round 5')], db_index=True, verbose_name='Tur'),
        ),
    ]
