# Generated by Django 4.2.7 on 2026-02-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_konu_options_alter_soru_baslik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnuvamaci',
            name='mac_baslangic_zamani',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Maç Başlangıç Zamanı'),
        ),
        migrations.AddField(
            model_name='turnuvamaci',
            name='oyuncu1_hazir',
            field=models.BooleanField(default=False, verbose_name='Oyuncu 1 Hazır'),
        ),
        migrations.AddField(
            model_name='turnuvamaci',
            name='oyuncu2_hazir',
            field=models.BooleanField(default=False, verbose_name='Oyuncu 2 Hazır'),
        ),
    ]
