# Generated by Django 4.2.7 on 2026-02-20 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0012_turnuvamaci_mac_baslangic_zamani_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnuvaSiralama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('elesme_round', models.IntegerField(default=0, verbose_name='Eleme Round')),
                ('oynanan_mac', models.IntegerField(default=0, verbose_name='Oynanan Maç')),
                ('kazanilan_mac', models.IntegerField(default=0, verbose_name='Kazanılan Maç')),
                ('kaybedilen_mac', models.IntegerField(default=0, verbose_name='Kaybedilen Maç')),
                ('toplam_skor', models.IntegerField(default=0, verbose_name='Toplam Skor')),
                ('ortalama_skor', models.FloatField(default=0.0, verbose_name='Ortalama Skor')),
                ('en_yuksek_skor', models.IntegerField(default=0, verbose_name='En Yüksek Skor')),
                ('toplam_dogru', models.IntegerField(default=0, verbose_name='Toplam Doğru')),
                ('toplam_yanlis', models.IntegerField(default=0, verbose_name='Toplam Yanlış')),
                ('dogru_yuzdesi', models.FloatField(default=0.0, verbose_name='Doğruluk Yüzdesi')),
                ('kazanilan_xp', models.IntegerField(default=0, verbose_name='Kazanılan XP')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turnuva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siralama', to='quiz.turnuva')),
            ],
            options={
                'verbose_name': 'Turnuva Sıralaması',
                'verbose_name_plural': 'Turnuva Sıralamaları',
                'ordering': ['sira'],
                'indexes': [models.Index(fields=['turnuva', 'sira'], name='siralama_turnuva_sira_idx')],
                'unique_together': {('turnuva', 'kullanici')},
            },
        ),
    ]
