# Generated by Django 4.2.7 on 2026-02-21 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0013_turnuvasiralama'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeydanOkuma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secilen_ders', models.CharField(default='karisik', max_length=30, verbose_name='Seçilen Ders')),
                ('sinav_tipi', models.CharField(default='AYT', max_length=10, verbose_name='Sınav Tipi')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('kabul_edildi', 'Kabul Edildi'), ('reddedildi', 'Reddedildi'), ('suresi_doldu', 'Süresi Doldu')], db_index=True, default='beklemede', max_length=20, verbose_name='Durum')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturma Tarihi')),
                ('alan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alinan_meydan_okumalar', to=settings.AUTH_USER_MODEL, verbose_name='Alan')),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_meydan_okumalar', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
                ('oda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meydan_okuma', to='quiz.karsilasmaodasi', verbose_name='Karşılaşma Odası')),
            ],
            options={
                'verbose_name': 'Meydan Okuma',
                'verbose_name_plural': 'Meydan Okumalar',
                'ordering': ['-olusturma_tarihi'],
                'indexes': [models.Index(fields=['alan', 'durum'], name='meydan_alan_durum_idx'), models.Index(fields=['gonderen', 'durum'], name='meydan_gonderen_durum_idx')],
            },
        ),
    ]
