# Generated by Django 4.2.7 on 2026-03-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_meydanokuma'),
    ]

    operations = [
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='bitis_zamani',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
