# Generated by Django 4.2.7 on 2026-04-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_soru_detayli_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='karsilasmaodasi',
            name='oda_kodu',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Oda Kodu'),
        ),
        migrations.AlterField(
            model_name='karsilasmaodasi',
            name='toplam_soru',
            field=models.IntegerField(default=10, verbose_name='Toplam Soru Sayısı'),
        ),
    ]
