# Generated by Django 4.2.7 on 2026-04-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_karsilasmaodasi_oda_kodu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulbakalimoyun',
            name='selected_ders',
            field=models.CharField(blank=True, choices=[('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('biyoloji', 'Biyoloji'), ('edebiyat', 'Edebiyat')], db_index=True, max_length=20, null=True, verbose_name='Seçilen Ders'),
        ),
        migrations.AlterField(
            model_name='karsilasmaodasi',
            name='secilen_ders',
            field=models.CharField(choices=[('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('biyoloji', 'Biyoloji'), ('karisik', 'Karışık'), ('edebiyat', 'Edebiyat')], db_index=True, default='karisik', max_length=20, verbose_name='Seçilen Ders'),
        ),
        migrations.AlterField(
            model_name='konu',
            name='ders',
            field=models.CharField(choices=[('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('biyoloji', 'Biyoloji'), ('edebiyat', 'Edebiyat')], db_index=True, default='matematik', max_length=20, verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='soru',
            name='ders',
            field=models.CharField(choices=[('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('biyoloji', 'Biyoloji'), ('edebiyat', 'Edebiyat')], db_index=True, default='matematik', max_length=20, verbose_name='Ders'),
        ),
    ]
