# Generated by Django 4.2.7 on 2026-04-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_karisik_sozel_sayisal_ders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulbakalimoyun',
            name='selected_ders',
            field=models.CharField(blank=True, choices=[('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('biyoloji', 'Biyoloji'), ('edebiyat', 'Edebiyat'), ('karisik', 'Karışık'), ('karisik_sayisal', 'Karışık Sayısal'), ('karisik_sozel', 'Karışık Sözel'), ('karisik_ea', 'Karışık EA'), ('karisik_sozel_ayt', 'Karışık Sözel AYT')], db_index=True, max_length=20, null=True, verbose_name='Seçilen Ders'),
        ),
        migrations.AlterField(
            model_name='karsilasmaodasi',
            name='secilen_ders',
            field=models.CharField(choices=[('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('biyoloji', 'Biyoloji'), ('edebiyat', 'Edebiyat'), ('karisik', 'Karışık'), ('karisik_sayisal', 'Karışık Sayısal'), ('karisik_sozel', 'Karışık Sözel'), ('karisik_ea', 'Karışık EA'), ('karisik_sozel_ayt', 'Karışık Sözel AYT')], db_index=True, default='karisik', max_length=20, verbose_name='Seçilen Ders'),
        ),
    ]
