# Generated by Django 4.2.7 on 2026-04-12 11:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0021_alter_bulbakalimoyun_selected_ders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konu',
            name='ders',
            field=models.CharField(choices=[('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('biyoloji', 'Biyoloji'), ('edebiyat', 'Edebiyat')], db_index=True, default='matematik', max_length=20, verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='soru',
            name='ders',
            field=models.CharField(choices=[('fizik', 'Fizik'), ('kimya', 'Kimya'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('biyoloji', 'Biyoloji'), ('edebiyat', 'Edebiyat')], db_index=True, default='matematik', max_length=20, verbose_name='Ders'),
        ),
        migrations.CreateModel(
            name='SoruBildir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sebep_kodu', models.CharField(choices=[('yanlis_cevap', 'Yanlış cevap işaretlenmiş'), ('hatali_soru', 'Soru hatalı/yanlış yazılmış'), ('konu_yanlisi', 'Yanlış konuya atanmış'), ('diger', 'Diğer')], default='diger', max_length=20)),
                ('aciklama', models.CharField(blank=True, max_length=300)),
                ('tarih', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('incelendi', models.BooleanField(db_index=True, default=False)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirimler', to='quiz.soru')),
            ],
            options={
                'verbose_name': 'Soru Bildirimi',
                'verbose_name_plural': 'Soru Bildirimleri',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='GununSorusu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(db_index=True, default=datetime.date.today, unique=True, verbose_name='Tarih')),
                ('bonus_xp', models.IntegerField(default=15, verbose_name='Bonus XP')),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.soru', verbose_name='Soru')),
            ],
            options={
                'verbose_name': 'Günün Sorusu',
                'verbose_name_plural': 'Günün Soruları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='GununSorusuCevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogru_mu', models.BooleanField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('gunun_sorusu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to='quiz.gununsorusu')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('secilen_cevap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.cevap')),
            ],
            options={
                'verbose_name': 'Günün Sorusu Cevabı',
                'verbose_name_plural': 'Günün Sorusu Cevapları',
                'unique_together': {('kullanici', 'gunun_sorusu')},
            },
        ),
    ]
