# Generated by Django 5.2.7 on 2025-11-29 12:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RozetKosul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=50, unique=True, verbose_name='Kategori')),
                ('seviye', models.CharField(max_length=20, verbose_name='Seviye')),
                ('gerekli_soru_sayisi', models.IntegerField(default=0, help_text='Çözülmesi gereken soru sayısı', verbose_name='Gerekli Soru Sayısı')),
                ('gerekli_dogru_sayisi', models.IntegerField(default=0, help_text='Yapılması gereken doğru sayısı', verbose_name='Gerekli Doğru Sayısı')),
                ('gerekli_puan', models.IntegerField(default=0, help_text='Kazanılması gereken puan', verbose_name='Gerekli Puan')),
                ('gerekli_oyun_sayisi', models.IntegerField(default=0, help_text='Oynanması gereken oyun sayısı', verbose_name='Gerekli Oyun Sayısı')),
                ('gerekli_galibiyet', models.IntegerField(default=0, help_text='Kazanılması gereken oyun sayısı', verbose_name='Gerekli Galibiyet')),
                ('gerekli_gun_sayisi', models.IntegerField(default=0, help_text='Aktif olunması gereken gün sayısı', verbose_name='Gerekli Gün Sayısı')),
                ('gerekli_basari_orani', models.FloatField(default=0, help_text='Başarı oranı (0-100)', verbose_name='Gerekli Başarı Oranı')),
                ('ozel_kosul', models.TextField(blank=True, help_text='Özel koşul açıklaması', verbose_name='Özel Koşul')),
                ('aciklama', models.TextField(help_text='Rozet açıklaması', verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Rozet Koşulu',
                'verbose_name_plural': 'Rozet Koşulları',
                'ordering': ['kategori', 'seviye'],
            },
        ),
        migrations.CreateModel(
            name='OgrenciProfili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alan', models.CharField(choices=[('sayisal', 'Sayısal'), ('sozel', 'Sözel'), ('esit_agirlik', 'Eşit Ağırlık'), ('dil', 'Dil')], default='sayisal', max_length=20, verbose_name='Alan')),
                ('profil_fotografi', models.ImageField(blank=True, null=True, upload_to='profil_fotograflari/', verbose_name='Profil Fotoğrafı')),
                ('toplam_puan', models.IntegerField(db_index=True, default=0, verbose_name='Toplam Puan')),
                ('cozulen_soru_sayisi', models.IntegerField(db_index=True, default=0, verbose_name='Çözülen Soru Sayısı')),
                ('toplam_dogru', models.IntegerField(default=0, verbose_name='Toplam Doğru')),
                ('toplam_yanlis', models.IntegerField(default=0, verbose_name='Toplam Yanlış')),
                ('haftalik_puan', models.IntegerField(db_index=True, default=0, verbose_name='Haftalık Puan')),
                ('haftalik_cozulen', models.IntegerField(default=0, verbose_name='Haftalık Çözülen')),
                ('haftalik_dogru', models.IntegerField(default=0, verbose_name='Haftalık Doğru')),
                ('haftalik_yanlis', models.IntegerField(default=0, verbose_name='Haftalık Yanlış')),
                ('hafta_baslangic', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hafta Başlangıç')),
                ('unvanlar', models.CharField(default='Çaylak', max_length=255, verbose_name='Unvanlar')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Kayıt Tarihi')),
                ('son_giris', models.DateTimeField(auto_now=True, verbose_name='Son Giriş')),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Öğrenci Profili',
                'verbose_name_plural': 'Öğrenci Profilleri',
                'ordering': ['-toplam_puan'],
            },
        ),
        migrations.CreateModel(
            name='KonuIstatistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders', models.CharField(db_index=True, max_length=50, verbose_name='Ders')),
                ('konu', models.CharField(max_length=100, verbose_name='Konu')),
                ('dogru_sayisi', models.IntegerField(default=0, verbose_name='Doğru Sayısı')),
                ('yanlis_sayisi', models.IntegerField(default=0, verbose_name='Yanlış Sayısı')),
                ('bos_sayisi', models.IntegerField(default=0, verbose_name='Boş Sayısı')),
                ('toplam_soru', models.IntegerField(default=0, verbose_name='Toplam Soru')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konu_istatistikleri', to='profile.ogrenciprofili', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Konu İstatistiği',
                'verbose_name_plural': 'Konu İstatistikleri',
            },
        ),
        migrations.CreateModel(
            name='DersIstatistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders', models.CharField(choices=[('matematik', 'Matematik'), ('fizik', 'Fizik'), ('kimya', 'Kimya'), ('biyoloji', 'Biyoloji'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('din', 'Din Kültürü'), ('ingilizce', 'İngilizce')], db_index=True, max_length=20, verbose_name='Ders')),
                ('toplam_puan', models.IntegerField(db_index=True, default=0, verbose_name='Toplam Puan')),
                ('cozulen_soru', models.IntegerField(default=0, verbose_name='Çözülen Soru')),
                ('dogru_sayisi', models.IntegerField(db_index=True, default=0, verbose_name='Doğru Sayısı')),
                ('yanlis_sayisi', models.IntegerField(default=0, verbose_name='Yanlış Sayısı')),
                ('bos_sayisi', models.IntegerField(default=0, verbose_name='Boş Sayısı')),
                ('haftalik_puan', models.IntegerField(default=0, verbose_name='Haftalık Puan')),
                ('haftalik_cozulen', models.IntegerField(default=0, verbose_name='Haftalık Çözülen')),
                ('haftalik_dogru', models.IntegerField(default=0, verbose_name='Haftalık Doğru')),
                ('haftalik_yanlis', models.IntegerField(default=0, verbose_name='Haftalık Yanlış')),
                ('hafta_baslangic', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hafta Başlangıç')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ders_istatistikleri', to='profile.ogrenciprofili', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Ders İstatistiği',
                'verbose_name_plural': 'Ders İstatistikleri',
            },
        ),
        migrations.CreateModel(
            name='OyunModuIstatistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oyun_modu', models.CharField(choices=[('karsilasma', 'Karşılaşma'), ('bul_bakalim', 'Bul Bakalım')], db_index=True, max_length=20, verbose_name='Oyun Modu')),
                ('toplam_puan', models.IntegerField(db_index=True, default=0, verbose_name='Toplam Puan')),
                ('oynanan_oyun_sayisi', models.IntegerField(default=0, verbose_name='Oynanan Oyun Sayısı')),
                ('kazanilan_oyun', models.IntegerField(default=0, verbose_name='Kazanılan Oyun')),
                ('kaybedilen_oyun', models.IntegerField(default=0, verbose_name='Kaybedilen Oyun')),
                ('cozulen_soru', models.IntegerField(default=0, verbose_name='Çözülen Soru')),
                ('dogru_sayisi', models.IntegerField(default=0, verbose_name='Doğru Sayısı')),
                ('yanlis_sayisi', models.IntegerField(default=0, verbose_name='Yanlış Sayısı')),
                ('haftalik_puan', models.IntegerField(db_index=True, default=0, verbose_name='Haftalık Puan')),
                ('haftalik_oyun_sayisi', models.IntegerField(default=0, verbose_name='Haftalık Oyun Sayısı')),
                ('haftalik_dogru', models.IntegerField(default=0, verbose_name='Haftalık Doğru')),
                ('haftalik_yanlis', models.IntegerField(default=0, verbose_name='Haftalık Yanlış')),
                ('hafta_baslangic', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hafta Başlangıç')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oyun_istatistikleri', to='profile.ogrenciprofili', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Oyun Modu İstatistiği',
                'verbose_name_plural': 'Oyun Modu İstatistikleri',
            },
        ),
        migrations.CreateModel(
            name='Rozet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('yeni_uye', 'Yeni Üye'), ('aktif_kullanici', 'Aktif Kullanıcı'), ('gun_asimi', 'Gün Aşımı'), ('hafta_sampionu', 'Hafta Şampiyonu'), ('soru_cozucu', 'Soru Çözücü'), ('dogru_ustasi', 'Doğru Ustası'), ('net_avcisi', 'Net Avcısı'), ('hatasiz_kusursuz', 'Hatasız Kusursuz'), ('matematik_dehasi', 'Matematik Dehası'), ('fizik_profesoru', 'Fizik Profesörü'), ('kimya_uzman', 'Kimya Uzmanı'), ('biyoloji_bilgini', 'Biyoloji Bilgini'), ('turkce_edebiyatci', 'Türkçe Edebiyatçısı'), ('tarih_bilgesi', 'Tarih Bilgesi'), ('cografya_gezgini', 'Coğrafya Gezgini'), ('felsefe_dusunuru', 'Felsefe Düşünürü'), ('karsilasma_savaslisi', 'Karşılaşma Savaşçısı'), ('bul_bakalim_ustasi', 'Bul Bakalım Ustası'), ('tabu_kral', 'Tabu Kralı'), ('galip_aslan', 'Galip Aslan'), ('lider_zirve', 'Lider Zirve'), ('top_10', 'Top 10'), ('top_50', 'Top 50'), ('zirve_fatih', 'Zirve Fatihi'), ('hizli_cevap', 'Hızlı Cevap'), ('gece_kusu', 'Gece Kuşu'), ('sabah_kusagu', 'Sabah Kuşağı'), ('maraton_kosucu', 'Maraton Koşucusu'), ('yardimci', 'Yardımcı'), ('ogretmen', 'Öğretmen'), ('ilham_verici', 'İlham Verici'), ('takım_oyuncusu', 'Takım Oyuncusu')], db_index=True, max_length=50, verbose_name='Kategori')),
                ('seviye', models.CharField(choices=[('caylak', 'Çaylak'), ('usta', 'Usta')], default='caylak', max_length=20, verbose_name='Seviye')),
                ('kazanilma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Kazanılma Tarihi')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rozetler', to='profile.ogrenciprofili', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Rozet',
                'verbose_name_plural': 'Rozetler',
                'ordering': ['-kazanilma_tarihi'],
            },
        ),
        migrations.AddIndex(
            model_name='ogrenciprofili',
            index=models.Index(fields=['-toplam_puan', '-haftalik_puan'], name='profil_puan_idx'),
        ),
        migrations.AddIndex(
            model_name='ogrenciprofili',
            index=models.Index(fields=['alan', '-toplam_puan'], name='profil_alan_puan_idx'),
        ),
        migrations.AddIndex(
            model_name='konuistatistik',
            index=models.Index(fields=['profil', 'ders'], name='konu_ist_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='konuistatistik',
            unique_together={('profil', 'ders', 'konu')},
        ),
        migrations.AddIndex(
            model_name='dersistatistik',
            index=models.Index(fields=['ders', '-dogru_sayisi'], name='ders_dogru_idx'),
        ),
        migrations.AddIndex(
            model_name='dersistatistik',
            index=models.Index(fields=['ders', '-toplam_puan'], name='ders_puan_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dersistatistik',
            unique_together={('profil', 'ders')},
        ),
        migrations.AddIndex(
            model_name='oyunmoduistatistik',
            index=models.Index(fields=['oyun_modu', '-toplam_puan'], name='oyun_mod_puan_idx'),
        ),
        migrations.AddIndex(
            model_name='oyunmoduistatistik',
            index=models.Index(fields=['oyun_modu', '-haftalik_puan'], name='oyun_mod_haft_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='oyunmoduistatistik',
            unique_together={('profil', 'oyun_modu')},
        ),
        migrations.AddIndex(
            model_name='rozet',
            index=models.Index(fields=['profil', '-kazanilma_tarihi'], name='rozet_profil_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rozet',
            unique_together={('profil', 'kategori', 'seviye')},
        ),
    ]
