# Generated by Django 5.2.7 on 2025-10-08 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OgrenciProfili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(blank=True, max_length=50, null=True)),
                ('soyad', models.CharField(blank=True, max_length=50, null=True)),
                ('hedef_puan', models.IntegerField(default=0)),
                ('toplam_puan', models.IntegerField(default=0)),
                ('haftalik_puan', models.IntegerField(default=0)),
                ('cozulen_soru_sayisi', models.IntegerField(default=0)),
                ('dogru_sayisi', models.IntegerField(default=0)),
                ('yanlis_sayisi', models.IntegerField(default=0)),
                ('alan', models.CharField(choices=[('sayisal', 'Sayısal'), ('esit_agirlik', 'Eşit Ağırlık'), ('sozel', 'Sözel'), ('dil', 'Dil')], default='esit_agirlik', max_length=20)),
                ('unvanlar', models.TextField(default='Yeni Köstebek')),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
