# Generated by Django 5.2.7 on 2025-10-18 16:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ogrenciprofili',
            options={'ordering': ['-toplam_puan'], 'verbose_name': 'Öğrenci Profili', 'verbose_name_plural': 'Öğrenci Profilleri'},
        ),
        migrations.RenameField(
            model_name='ogrenciprofili',
            old_name='hedef_puan',
            new_name='haftalik_cozulen',
        ),
        migrations.RemoveField(
            model_name='ogrenciprofili',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='ogrenciprofili',
            name='soyad',
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='hafta_baslangic',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='haftalik_dogru',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='haftalik_yanlis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='son_giris',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ogrenciprofili',
            name='alan',
            field=models.CharField(choices=[('sayisal', 'Sayısal'), ('sozel', 'Sözel'), ('esit_agirlik', 'Eşit Ağırlık'), ('dil', 'Dil')], default='sayisal', max_length=20),
        ),
        migrations.AlterField(
            model_name='ogrenciprofili',
            name='unvanlar',
            field=models.CharField(default='Çaylak', max_length=255),
        ),
        migrations.CreateModel(
            name='DersIstatistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders', models.CharField(choices=[('matematik', 'Matematik'), ('fizik', 'Fizik'), ('kimya', 'Kimya'), ('biyoloji', 'Biyoloji'), ('turkce', 'Türkçe'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('din', 'Din Kültürü'), ('ingilizce', 'İngilizce')], max_length=20)),
                ('toplam_puan', models.IntegerField(default=0)),
                ('cozulen_soru', models.IntegerField(default=0)),
                ('dogru_sayisi', models.IntegerField(default=0)),
                ('yanlis_sayisi', models.IntegerField(default=0)),
                ('bos_sayisi', models.IntegerField(default=0)),
                ('haftalik_puan', models.IntegerField(default=0)),
                ('haftalik_cozulen', models.IntegerField(default=0)),
                ('haftalik_dogru', models.IntegerField(default=0)),
                ('haftalik_yanlis', models.IntegerField(default=0)),
                ('hafta_baslangic', models.DateTimeField(default=django.utils.timezone.now)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ders_istatistikleri', to='profile.ogrenciprofili')),
            ],
            options={
                'verbose_name': 'Ders İstatistiği',
                'verbose_name_plural': 'Ders İstatistikleri',
                'unique_together': {('profil', 'ders')},
            },
        ),
        migrations.CreateModel(
            name='OyunModuIstatistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oyun_modu', models.CharField(choices=[('karsilasma', 'Karşılaşma'), ('bul_bakalim', 'Bul Bakalım')], max_length=20)),
                ('toplam_puan', models.IntegerField(default=0)),
                ('oynanan_oyun_sayisi', models.IntegerField(default=0)),
                ('kazanilan_oyun', models.IntegerField(default=0)),
                ('kaybedilen_oyun', models.IntegerField(default=0)),
                ('cozulen_soru', models.IntegerField(default=0)),
                ('dogru_sayisi', models.IntegerField(default=0)),
                ('yanlis_sayisi', models.IntegerField(default=0)),
                ('haftalik_puan', models.IntegerField(default=0)),
                ('haftalik_oyun_sayisi', models.IntegerField(default=0)),
                ('haftalik_dogru', models.IntegerField(default=0)),
                ('haftalik_yanlis', models.IntegerField(default=0)),
                ('hafta_baslangic', models.DateTimeField(default=django.utils.timezone.now)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oyun_istatistikleri', to='profile.ogrenciprofili')),
            ],
            options={
                'verbose_name': 'Oyun Modu İstatistiği',
                'verbose_name_plural': 'Oyun Modu İstatistikleri',
                'unique_together': {('profil', 'oyun_modu')},
            },
        ),
    ]
