# Generated by Django 4.2.7 on 2025-12-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_remove_ogrenciprofili_profil_puan_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ogrenciprofili',
            name='profil_puan_idx',
        ),
        migrations.AddIndex(
            model_name='ogrenciprofili',
            index=models.Index(fields=['-toplam_puan'], name='profil_toplam_idx'),
        ),
        migrations.AddIndex(
            model_name='ogrenciprofili',
            index=models.Index(fields=['-haftalik_puan'], name='profil_haftalik_idx'),
        ),
        migrations.AddIndex(
            model_name='ogrenciprofili',
            index=models.Index(fields=['-aylik_puan'], name='profil_aylik_idx'),
        ),
        migrations.AddIndex(
            model_name='ogrenciprofili',
            index=models.Index(fields=['-gunluk_puan'], name='profil_gunluk_idx'),
        ),
    ]
