# Generated by Django 5.2.7 on 2025-10-19 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_ogrenciprofili_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RozetKosul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=50, unique=True)),
                ('seviye', models.CharField(max_length=20)),
                ('gerekli_soru_sayisi', models.IntegerField(default=0, help_text='Çözülmesi gereken soru sayısı')),
                ('gerekli_dogru_sayisi', models.IntegerField(default=0, help_text='Yapılması gereken doğru sayısı')),
                ('gerekli_puan', models.IntegerField(default=0, help_text='Kazanılması gereken puan')),
                ('gerekli_oyun_sayisi', models.IntegerField(default=0, help_text='Oynanması gereken oyun sayısı')),
                ('gerekli_galibiyet', models.IntegerField(default=0, help_text='Kazanılması gereken oyun sayısı')),
                ('gerekli_gun_sayisi', models.IntegerField(default=0, help_text='Aktif olunması gereken gün sayısı')),
                ('gerekli_basari_orani', models.FloatField(default=0, help_text='Başarı oranı (0-100)')),
                ('ozel_kosul', models.TextField(blank=True, help_text='Özel koşul açıklaması')),
                ('aciklama', models.TextField(help_text='Rozet açıklaması')),
            ],
            options={
                'verbose_name': 'Rozet Koşulu',
                'verbose_name_plural': 'Rozet Koşulları',
            },
        ),
        migrations.CreateModel(
            name='Rozet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('yeni_uye', 'Yeni Üye'), ('aktif_kullanici', 'Aktif Kullanıcı'), ('gun_asimi', 'Gün Aşımı'), ('hafta_sampionu', 'Hafta Şampiyonu'), ('soru_cozucu', 'Soru Çözücü'), ('dogru_ustasi', 'Doğru Ustası'), ('net_avcisi', 'Net Avcısı'), ('hatasiz_kusursuz', 'Hatasız Kusursuz'), ('matematik_dehasi', 'Matematik Dehası'), ('fizik_profesoru', 'Fizik Profesörü'), ('kimya_uzman', 'Kimya Uzmanı'), ('biyoloji_bilgini', 'Biyoloji Bilgini'), ('turkce_edebiyatci', 'Türkçe Edebiyatçısı'), ('tarih_bilgesi', 'Tarih Bilgesi'), ('cografya_gezgini', 'Coğrafya Gezgini'), ('felsefe_dusunuru', 'Felsefe Düşünürü'), ('karsilasma_savaslisi', 'Karşılaşma Savaşçısı'), ('bul_bakalim_ustasi', 'Bul Bakalım Ustası'), ('tabu_kral', 'Tabu Kralı'), ('galip_aslan', 'Galip Aslan'), ('lider_zirve', 'Lider Zirve'), ('top_10', 'Top 10'), ('top_50', 'Top 50'), ('zirve_fatih', 'Zirve Fatihi'), ('hizli_cevap', 'Hızlı Cevap'), ('gece_kusu', 'Gece Kuşu'), ('sabah_kusagu', 'Sabah Kuşağı'), ('maraton_kosucu', 'Maraton Koşucusu'), ('yardimci', 'Yardımcı'), ('ogretmen', 'Öğretmen'), ('ilham_verici', 'İlham Verici'), ('takım_oyuncusu', 'Takım Oyuncusu')], max_length=50)),
                ('seviye', models.CharField(choices=[('caylak', 'Çaylak'), ('usta', 'Usta')], default='caylak', max_length=20)),
                ('kazanilma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rozetler', to='profile.ogrenciprofili')),
            ],
            options={
                'verbose_name': 'Rozet',
                'verbose_name_plural': 'Rozetler',
                'ordering': ['-kazanilma_tarihi'],
                'unique_together': {('profil', 'kategori', 'seviye')},
            },
        ),
    ]
