# Generated by Django 4.2.7 on 2025-12-15 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0003_remove_ogrenciprofili_profil_puan_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('rozet', 'Yeni Rozet'), ('liderlik', 'Liderlik Değişimi'), ('seviye', 'Seviye Atlama'), ('basari', 'Özel Başarı'), ('sistem', 'Sistem Bildirimi')], default='sistem', max_length=20, verbose_name='Bildirim Tipi')),
                ('baslik', models.CharField(max_length=100, verbose_name='Başlık')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('icon', models.CharField(default='🔔', max_length=10, verbose_name='İkon')),
                ('okundu_mu', models.BooleanField(default=False, verbose_name='Okundu mu')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturma Tarihi')),
                ('iliskili_rozet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.rozet', verbose_name='İlişkili Rozet')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirimler', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-olusturma_tarihi'],
                'indexes': [models.Index(fields=['kullanici', '-olusturma_tarihi'], name='bildirim_kullanici_idx'), models.Index(fields=['okundu_mu'], name='bildirim_okundu_idx')],
            },
        ),
    ]
