# Generated by Django 5.2.7 on 2025-10-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_rozetkosul_rozet'),
    ]

    operations = [
    ]
