# Generated by Django 5.2.7 on 2025-10-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_add_rozet_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonuIstatistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders', models.CharField(max_length=50)),
                ('konu', models.CharField(max_length=100)),
                ('dogru_sayisi', models.IntegerField(default=0)),
                ('yanlis_sayisi', models.IntegerField(default=0)),
                ('bos_sayisi', models.IntegerField(default=0)),
                ('toplam_soru', models.IntegerField(default=0)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.ogrenciprofili')),
            ],
            options={
                'unique_together': {('profil', 'ders', 'konu')},
            },
        ),
    ]
