# Generated by Django 4.2.7 on 2025-12-16 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0004_bildirim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arkadaslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('kabul_edildi', 'Kabul Edildi'), ('reddedildi', 'Reddedildi')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('alan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alinan_arkadaslik_istekleri', to=settings.AUTH_USER_MODEL, verbose_name='Alan')),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_arkadaslik_istekleri', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Arkadaşlık',
                'verbose_name_plural': 'Arkadaşlıklar',
                'ordering': ['-olusturma_tarihi'],
                'indexes': [models.Index(fields=['gonderen', 'durum'], name='arkadaslik_gonderen_idx'), models.Index(fields=['alan', 'durum'], name='arkadaslik_alan_idx')],
                'unique_together': {('gonderen', 'alan')},
            },
        ),
    ]
