# Generated by Django 4.2.7 on 2025-12-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_arkadaslik'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenciprofili',
            name='seviye',
            field=models.IntegerField(default=1, help_text='Kullanıcının mevcut seviyesi', verbose_name='Seviye'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='xp',
            field=models.IntegerField(default=0, help_text='Toplam kazanılan XP', verbose_name='Deneyim Puanı (XP)'),
        ),
    ]
