# Generated by Django 4.2.7 on 2025-12-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_ogrenciprofili_seviye_ogrenciprofili_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenciprofili',
            name='ardasik_gun_sayisi',
            field=models.IntegerField(default=0, help_text='Kaç gündür üst üste giriş yapıyor', verbose_name='Ardışık Gün Sayısı (Streak)'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='en_uzun_streak',
            field=models.IntegerField(default=0, help_text='Şimdiye kadarki en uzun ardışık gün sayısı', verbose_name='En Uzun Streak'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='son_giris_tarihi',
            field=models.DateField(blank=True, help_text='Kullanıcının son giriş yaptığı tarih', null=True, verbose_name='Son Giriş Tarihi'),
        ),
    ]
