# Generated by Django 4.2.7 on 2026-02-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_ogrenciprofili_ardasik_gun_sayisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenciprofili',
            name='en_uzun_seri',
            field=models.IntegerField(default=0, verbose_name='En Uzun Seri'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='mevcut_seri',
            field=models.IntegerField(default=0, verbose_name='Mevcut Seri'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='son_aktif_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Son Aktif Tarih'),
        ),
    ]
