# Generated by Django 4.2.7 on 2026-02-21 20:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_ogrenciprofili_en_uzun_seri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GunlukGorevSablonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200, verbose_name='Görev İsmi')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('gorev_tipi', models.CharField(choices=[('soru_coz', 'Soru Çöz'), ('dogru_cevap', 'Doğru Cevap Ver'), ('bul_bakalim_oyna', 'Bul Bakalım Oyna'), ('karsilasma_oyna', 'Karşılaşma Oyna'), ('karsilasma_kazan', 'Karşılaşma Kazan'), ('streak_koru', 'Streak Koru'), ('farkli_ders', 'Farklı Dersten Soru Çöz')], db_index=True, max_length=30, verbose_name='Görev Tipi')),
                ('hedef_sayi', models.IntegerField(default=1, verbose_name='Hedef Sayı')),
                ('odul_xp', models.IntegerField(default=50, verbose_name='Ödül XP')),
                ('odul_puan', models.IntegerField(default=0, verbose_name='Ödül Puan')),
                ('icon', models.CharField(default='🎯', max_length=10, verbose_name='İkon')),
                ('aktif_mi', models.BooleanField(db_index=True, default=True, verbose_name='Aktif Mi')),
                ('zorluk', models.CharField(choices=[('kolay', 'Kolay'), ('orta', 'Orta'), ('zor', 'Zor')], default='orta', max_length=10, verbose_name='Zorluk')),
            ],
            options={
                'verbose_name': 'Günlük Görev Şablonu',
                'verbose_name_plural': 'Günlük Görev Şablonları',
            },
        ),
        migrations.CreateModel(
            name='KullaniciGunlukGorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Görev Tarihi')),
                ('mevcut_ilerleme', models.IntegerField(default=0, verbose_name='Mevcut İlerleme')),
                ('tamamlandi_mi', models.BooleanField(db_index=True, default=False, verbose_name='Tamamlandı mı')),
                ('tamamlanma_zamani', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Zamanı')),
                ('odul_alindi_mi', models.BooleanField(default=False, verbose_name='Ödül Alındı mı')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gunluk_gorevler', to='profile.ogrenciprofili', verbose_name='Profil')),
                ('sablon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.gunlukgorevsablonu', verbose_name='Görev Şablonu')),
            ],
            options={
                'verbose_name': 'Kullanıcı Günlük Görevi',
                'verbose_name_plural': 'Kullanıcı Günlük Görevleri',
                'ordering': ['tamamlandi_mi', '-tarih'],
                'indexes': [models.Index(fields=['profil', 'tarih'], name='gorev_profil_tarih_idx'), models.Index(fields=['profil', 'tamamlandi_mi'], name='gorev_profil_tamam_idx')],
                'unique_together': {('profil', 'sablon', 'tarih')},
            },
        ),
        migrations.CreateModel(
            name='CalismaKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(db_index=True, verbose_name='Tarih')),
                ('cozulen_soru', models.IntegerField(default=0, verbose_name='Çözülen Soru')),
                ('dogru_sayisi', models.IntegerField(default=0, verbose_name='Doğru Sayısı')),
                ('yanlis_sayisi', models.IntegerField(default=0, verbose_name='Yanlış Sayısı')),
                ('kazanilan_xp', models.IntegerField(default=0, verbose_name='Kazanılan XP')),
                ('oynanan_oyun', models.IntegerField(default=0, verbose_name='Oynanan Oyun')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calisma_kayitlari', to='profile.ogrenciprofili', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Çalışma Kaydı',
                'verbose_name_plural': 'Çalışma Kayıtları',
                'ordering': ['-tarih'],
                'indexes': [models.Index(fields=['profil', '-tarih'], name='calisma_profil_tarih_idx')],
                'unique_together': {('profil', 'tarih')},
            },
        ),
    ]
