# Generated by Django 4.2.7 on 2026-02-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_gunlukgorevsablonu_kullanicigunlukgorev_calismakaydi'),
    ]

    operations = [
        migrations.CreateModel(
            name='XPGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.IntegerField(verbose_name='XP Miktarı')),
                ('sebep', models.CharField(max_length=200, verbose_name='Sebep')),
                ('tarih', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tarih')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_gecmisi', to='profile.ogrenciprofili', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'XP Geçmişi',
                'verbose_name_plural': 'XP Geçmişleri',
                'ordering': ['-tarih'],
                'indexes': [models.Index(fields=['profil', '-tarih'], name='xp_profil_tarih_idx')],
            },
        ),
    ]
