# Generated by Django 4.2.7 on 2026-02-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_xpgecmisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenciprofili',
            name='tema',
            field=models.CharField(choices=[('mor', '🟣 Mor'), ('okyanus', '🔵 Okyanus'), ('ates', '🔴 Ateş'), ('orman', '🟢 Orman'), ('gece', '🌙 Gece'), ('gunbatimi', '🌅 Gün Batımı'), ('altin', '⭐ Altın'), ('pembe', '🌸 Pembe')], default='mor', max_length=20, verbose_name='Profil Teması'),
        ),
    ]
