# Generated by Django 4.2.7 on 2026-02-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_ogrenciprofili_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenciprofili',
            name='son_aktif',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Aktif Zaman'),
        ),
    ]
