# Generated by Django 4.2.7 on 2026-02-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_ogrenciprofili_son_aktif'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirim',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yönlendirme Linki'),
        ),
        migrations.AddField(
            model_name='bildirim',
            name='silindi_mi',
            field=models.BooleanField(default=False, verbose_name='Silindi mi'),
        ),
        migrations.AlterField(
            model_name='bildirim',
            name='tip',
            field=models.CharField(choices=[('rozet', 'Yeni Rozet'), ('liderlik', 'Liderlik Değişimi'), ('seviye', 'Seviye Atlama'), ('basari', 'Özel Başarı'), ('sistem', 'Sistem Bildirimi'), ('arkadas', 'Arkadaşlık'), ('meydan_okuma', 'Meydan Okuma'), ('streak', 'Streak'), ('xp', 'XP Kazanıldı'), ('gorev', 'Görev')], default='sistem', max_length=20, verbose_name='Bildirim Tipi'),
        ),
    ]
