# Generated by Django 4.2.7 on 2026-04-06 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0014_remove_profil_fotografi_add_avatar'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ogrenciprofili',
            name='profil_puan_idx',
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='aktif_mi',
            field=models.BooleanField(default=True, verbose_name='Aktif Mi'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='aylik_cozulen',
            field=models.IntegerField(default=0, verbose_name='Aylık Çözülen'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='aylik_dogru',
            field=models.IntegerField(default=0, verbose_name='Aylık Doğru'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='aylik_puan',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Aylık Puan'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='aylik_yanlis',
            field=models.IntegerField(default=0, verbose_name='Aylık Yanlış'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='gunluk_cozulen',
            field=models.IntegerField(default=0, verbose_name='Günlük Çözülen'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='gunluk_dogru',
            field=models.IntegerField(default=0, verbose_name='Günlük Doğru'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='gunluk_puan',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Günlük Puan'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='gunluk_yanlis',
            field=models.IntegerField(default=0, verbose_name='Günlük Yanlış'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='son_aylik_reset',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Son Aylık Reset'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='son_gunluk_reset',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Son Günlük Reset'),
        ),
        migrations.AddField(
            model_name='ogrenciprofili',
            name='son_haftalik_reset',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Son Haftalık Reset'),
        ),
        migrations.AddIndex(
            model_name='ogrenciprofili',
            index=models.Index(fields=['-toplam_puan'], name='profil_toplam_idx'),
        ),
        migrations.AddIndex(
            model_name='ogrenciprofili',
            index=models.Index(fields=['-haftalik_puan'], name='profil_haftalik_idx'),
        ),
        migrations.AddIndex(
            model_name='ogrenciprofili',
            index=models.Index(fields=['-aylik_puan'], name='profil_aylik_idx'),
        ),
        migrations.AddIndex(
            model_name='ogrenciprofili',
            index=models.Index(fields=['-gunluk_puan'], name='profil_gunluk_idx'),
        ),
    ]
