# Generated by Django 4.2.7 on 2026-02-25 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazaUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('kategori', models.CharField(choices=[('unvan', 'Unvan'), ('cerceve', 'Profil Çerçevesi'), ('tema', 'Tema')], max_length=20, verbose_name='Kategori')),
                ('fiyat', models.IntegerField(verbose_name='Fiyat (Puan)')),
                ('icon', models.CharField(default='🎁', max_length=10, verbose_name='İkon')),
                ('unvan_metni', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unvan Metni')),
                ('unvan_renk', models.CharField(default='#667eea', max_length=20, verbose_name='Unvan Rengi')),
                ('cerceve_css', models.CharField(blank=True, max_length=500, null=True, verbose_name='Çerçeve CSS')),
                ('cerceve_renk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Çerçeve Rengi')),
                ('tema_primary', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ana Renk')),
                ('tema_secondary', models.CharField(blank=True, max_length=20, null=True, verbose_name='İkincil Renk')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mağaza Ürünü',
                'verbose_name_plural': 'Mağaza Ürünleri',
                'ordering': ['kategori', 'fiyat'],
            },
        ),
        migrations.CreateModel(
            name='KullaniciEnvanter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif_cerceve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktif_cerceve_kullanicilari', to='magaza.magazaurun', verbose_name='Aktif Çerçeve')),
                ('aktif_tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktif_tema_kullanicilari', to='magaza.magazaurun', verbose_name='Aktif Tema')),
                ('aktif_unvan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktif_unvan_kullanicilari', to='magaza.magazaurun', verbose_name='Aktif Unvan')),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envanter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Envanteri',
                'verbose_name_plural': 'Kullanıcı Envanterleri',
            },
        ),
        migrations.CreateModel(
            name='SatinAlma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odenen_puan', models.IntegerField(verbose_name='Ödenen Puan')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satin_almalar', to=settings.AUTH_USER_MODEL)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satin_almalar', to='magaza.magazaurun')),
            ],
            options={
                'verbose_name': 'Satın Alma',
                'verbose_name_plural': 'Satın Almalar',
                'ordering': ['-tarih'],
                'unique_together': {('kullanici', 'urun')},
            },
        ),
    ]
