# Generated by Django 4.2.7 on 2026-04-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaza', '0002_magazaurun_avatar_emoji_kategori_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazaurun',
            name='kategori',
            field=models.CharField(choices=[('unvan', 'Unvan'), ('cerceve', 'Profil Çerçevesi'), ('tema', 'Tema'), ('avatar', 'Avatar')], max_length=20, verbose_name='Kategori'),
        ),
    ]
